# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nginx:
  replicaCount: 3
  image:
    tag: latest
  pullPolicy: Always
  prefix: test

debug:
  replicaCount: 1
  image:
    tag: latest
  pullPolicy: Always
